// The list of topics and tasks shown on the home page.
// Each task lives in src/topics/<slug>/Task<N>.jsx

export const topics = [
  {
    slug: '01-jsx-components',
    title: 'JSX and Components',
    level: 'Beginner',
    summary: 'JSX rules, function components, exporting and importing',
    tasks: [
      'Hello, Delhi College',
      'Student ID Card',
      'Price Calculator',
      'Matatu Route Board',
      'Page Layout',
      'Campus Parts',
      'Weekly Timetable',
      'Staff Profile Page',
    ],
  },
  {
    slug: '02-props',
    title: 'Props',
    level: 'Beginner',
    summary: 'Passing data, destructuring, children, default values',
    tasks: [
      'Greeting Cards',
      'Course Cards',
      'Matatu Ticket',
      'Tyre Price Tag',
      'Notice Board',
      'Student Report',
      'Status Badges',
      'M-Pesa Receipt',
    ],
  },
  {
    slug: '03-state',
    title: 'State with useState',
    level: 'Beginner',
    summary: 'Counters, toggles, updating objects and arrays',
    tasks: [
      'Class Attendance Counter',
      'Lab Lights Switch',
      'Matatu Seat Counter',
      'M-Pesa Wallet',
      'Student Profile Editor',
      'Shopping List',
      'Tyre Order Builder',
      'Attendance Register',
    ],
  },
  {
    slug: '04-events-forms',
    title: 'Events and Forms',
    level: 'Beginner',
    summary: 'onClick, onChange, controlled inputs, form submit',
    tasks: [
      'Welcome Button',
      'Fare Finder',
      'Name Badge Preview',
      'SMS Composer',
      'Course Picker',
      'Enquiry Form',
      'Phone Number Check',
      'Registration Form',
    ],
  },
  {
    slug: '05-conditional-rendering',
    title: 'Conditional Rendering',
    level: 'Beginner',
    summary: 'if, ternary, &&, showing and hiding',
    tasks: [
      'Fee Status',
      'Login Greeting',
      'Message Badge',
      'FAQ Answers',
      'Grade Calculator',
      'Stock Labels',
      'Exam Reminder Banner',
      'Info Tabs',
    ],
  },
  {
    slug: '06-lists-keys',
    title: 'Lists and Keys',
    level: 'Beginner',
    summary: 'map, keys, filtering and sorting lists',
    tasks: [
      'Departments List',
      'Course Table',
      'Department Filter',
      'Student Search',
      'Tyre Catalogue Sort',
      'Assignment Tracker',
      'Shopping Cart Totals',
      'Timetable by Day',
    ],
  },
  {
    slug: '07-lifting-state',
    title: 'Lifting State and Composition',
    level: 'Intermediate',
    summary: 'Sharing state between components, parent and child',
    tasks: [
      'Shared Counter',
      'Currency Converter',
      'Course Picker and Details',
      'Search and Results',
      'Add a Student',
      'Pop-up Dialog',
      'Tyre Shop Cart',
      'One-at-a-time Accordion',
    ],
  },
  {
    slug: '08-useeffect-data',
    title: 'useEffect and Loading Data',
    level: 'Intermediate',
    summary: 'Side effects, loading local JSON, loading and error states',
    tasks: [
      'Page Title Updater',
      'Stopwatch',
      'Course List from JSON',
      'Notices with Error Handling',
      'Class Lists',
      'Tyre Search with Delay',
      'Saved Notes',
      'Screen Size Watcher',
    ],
  },
  {
    slug: '09-react-router',
    title: 'React Router',
    level: 'Intermediate',
    summary: 'Routes, links, URL parameters, a 404 page',
    tasks: [
      'First Pages',
      'Active Menu',
      'Course Details',
      'Page Not Found',
      'Enrol and Redirect',
      'Student Dashboard',
      'Tyre Filter in the URL',
      'Matatu Route Pages',
    ],
  },
  {
    slug: '10-context-reducer',
    title: 'Context and useReducer',
    level: 'Intermediate',
    summary: 'Global state, a theme and a shopping cart',
    tasks: [
      'Theme Switcher',
      'Signed-in User',
      'English / Kiswahili',
      'Step Counter',
      'M-Pesa Wallet Reducer',
      'To-Do Reducer',
      'Tyre Shop Cart',
      'Library Borrowing',
    ],
  },
  {
    slug: '11-mini-project',
    title: 'Mini Project',
    level: 'Intermediate',
    summary: 'A Delhi College course catalogue that uses everything',
    tasks: [
      'Catalogue Grid',
      'Search Box',
      'Filters',
      'Sort and Count',
      'Course Details Page',
      'Enrolment Form',
      'My Enrolments',
      'Complete Catalogue App',
    ],
  },
]
